### PR TITLE
Linux 3.10.105

### PR DESCRIPTION
**Pull request by DroidThug**

### CODE REVIEW

**Comment by DroidThug** [comment]
Ab marega mujko? :rofl:

**Comment by MSF-Jarvis** [comment]
@GreekDragonGR lookie here we got Lord Dorimanx

**Comment by dragonGR** [comment]
🙏🙏🙏🙏🙏🙏 Sir 🙏🙏🙏🙏🙏

**Comment by DroidThug** [comment]
#3 is the real thing :laughing:

**Pull request closed without merging**
